name: GithubActions_Final
on: 
  push:
   branches:
    - master
jobs:
  Github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}